version: '3.9'

services:

  postgis:
    container_name: postgis
    build: .
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgis_db
    volumes: 
    - ./data/:/var/lib/postgresql/data
    - ./init/:/docker-entrypoint-initdb.d
    ports: 
    - 5434:5432

  adminer:
    image: adminer:standalone
    environment:
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: postgis_db
    ports:
    - 8080:8080
    links:
    - "postgis:db"